name: blur-wallet
version: 0.1.9.9.2
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a privacy-focused cryptocurrency based on code from Monero. The Blur
    Network focuses on fostering an educational environment within its community,
    to lower the barriers to entry for those with an interest in cryptocurrency/mining.
    BLUR can be mined with just a CPU, and does not require specialized hardware.
    Join the Fight for Financial Freedom.
grade: stable
confinement: strict

apps:
    blur-wallet:
        command: |
          blur-gui-wallet
        environment:
          PATH: ${PATH}:${SNAP}/bin:${SNAP}/usr/lib/x86_64-linux-gnu/qt5/bin:${SNAP}/usr/bin
          LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/lib:${SNAP}/usr/x86_64-linux-gnu:${SNAP}/usr/lib:${SNAP}/usr/lib/x86_64-linux-gnu/qt5/lib:${SNAP}/bin/libs
          QT_PLUGIN_PATH: ${QT_PLUGIN_PATH}:${SNAP}/bin/plugins
          QML2_IMPORT_PATH: ${QML_IMPORT_PATH}:${SNAP}/bin/qml
        plugs:
            - home
            - network
            - network-bind
            - desktop
            - desktop-legacy
            - x11
            - opengl

parts:
    blur-wallet:
        build-packages: [build-essential, git, cmake, pkg-config, libboost-all-dev, libssl1.0-dev, libsodium-dev, qtbase5-dev, qtdeclarative5-dev, qtquickcontrols2-5-dev, qml-module-qtquick-controls, qml-module-qtquick-controls2, qml-module-qtquick-dialogs, qml-module-qtquick-xmllistmodel, qml-module-qt-labs-folderlistmodel, qml-module-qt-labs-settings,  qttools5-dev-tools]
        plugin: dump
        filesets:
          binary-folder:
            - bin/*
        source: .
        override-build: sudo /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders | sudo tee loaders.cache
        stage-packages:
            - libboost-chrono1.62.0
            - libboost-filesystem1.62.0
            - libboost-system1.62.0
            - libboost-date-time1.62.0
            - libboost-program-options1.62.0
            - libboost-regex1.62.0
            - libboost-serialization1.62.0
            - libboost-atomic1.62.0
            - libboost-locale1.62.0
            - libboost-thread1.62.0
            - libssl1.0.2
            - libsodium18
            - libgcc1
            - libglib2.0-dev
            - libqt5concurrent5
            - libqt5core5a
            - libqt5sql5
            - libqt5dbus5
            - libqt5gui5
            - libqt5xml5
            - libqt5quick5
            - libqt5quickwidgets5
            - libqt5quickcontrols2-5
            - libqt5quicktemplates2-5
            - libqt5xmlpatterns5
            - qtbase-abi-5-7-1
            - qtdeclarative-abi-5-7-0
            - libgdk-pixbuf2.0-dev
            - libgtk-3-0
            - libglu1-mesa-dev
        organize:
            start_gui.sh: bin/start_gui.sh
            loaders.cache: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
            libs/*: usr/lib/
        prime:
            - $binary-folder
            - usr/lib
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        prime:
            - bin
            - blurd
            - blur-gui-wallet
     
