name: blur-wallet
version: 0.1.9.9.2
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a privacy-focused cryptocurrency based on code from Monero. The Blur
    Network focuses on fostering an educational environment within its community,
    to lower the barriers to entry for those with an interest in cryptocurrency/mining.
    BLUR can be mined with just a CPU, and does not require specialized hardware.
    Join the Fight for Financial Freedom.
grade: stable
confinement: strict
base: core18

apps:
    blur-wallet:
        command: |
           ${SNAP}/blur-wallet-wrapper
        environment:
          PATH: ${PATH}:${SNAP}/bin:${SNAP}/usr/lib/${HOSTTYPE}-${OSTYPE}/qt5/bin:${SNAP}/usr/bin
          LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/lib:${SNAP}/usr/${HOSTTYPE}-${OSTYPE}:${SNAP}/usr/lib:${SNAP}/usr/lib/${HOSTTYPE}-${OSTYPE}/qt5/lib:${SNAP}/bin/libs:${SNAP}/usr/lib/${HOSTTYPE}-${OSTYPE}/mesa:${SNAP}/usr/lib/${HOSTTYPE}-${OSTYPE}/mesa-egl
          LIBGL_DRIVERS_PATH: $SNAP/usr/lib/${HOSTTYPE}-${OSTYPE}/dri
          XLOCALEDIR: ${SNAP}/usr/share/X11/locale
          LOCPATH: ${SNAP}/usr/lib/locale
          APP_DIR: ${SNAP}
          QT_XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb
          QT_PLUGIN_PATH: ${QT_PLUGIN_PATH}:${SNAP}/bin/plugins
          QML2_IMPORT_PATH: ${QML_IMPORT_PATH}:${SNAP}/bin/qml
        plugs:
            - home
            - network
            - desktop
            - desktop-legacy
            - opengl
            - wayland
            - x11
        extensions: [gnome-3-28]

parts:
    blur-wallet:
        build-packages: [build-essential, git, cmake, pkg-config, libboost-all-dev, libssl1.0-dev, libsodium-dev, qtbase5-dev, qtdeclarative5-dev, qtquickcontrols2-5-dev, qml-module-qtquick-controls, qml-module-qtquick-controls2, qml-module-qtquick-dialogs, qml-module-qtquick-xmllistmodel, qml-module-qt-labs-folderlistmodel, qml-module-qt-labs-settings,  qttools5-dev-tools]
        plugin: dump
        source: .
        stage-packages:
            - libboost-chrono1.62.0
            - libboost-filesystem1.62.0
            - libboost-system1.62.0
            - libboost-date-time1.62.0
            - libboost-program-options1.62.0
            - libboost-regex1.62.0
            - libboost-serialization1.62.0
            - libboost-atomic1.62.0
            - libboost-locale1.62.0
            - libboost-thread1.62.0
            - libssl-dev
            - libsodium-dev
            - libgcc1
            - libqt5concurrent5
            - libqt5core5a
            - libqt5sql5
            - libqt5dbus5
            - libqt5gui5
            - libqt5xml5
            - libqt5quick5
            - libqt5quickwidgets5
            - libqt5quickcontrols2-5
            - libqt5quicktemplates2-5
            - libqt5xmlpatterns5
            - qtdeclarative5-dev
            - zlib1g
        organize:
            bin/libs: lib
            snap/bin/blur-wallet-wrapper: ${SNAPCRAFT_PART_INSTALL}/blur-wallet-wrapper
        prime:
            - bin
            - usr/lib
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        prime:
            - bin
            - blurd
            - blur-gui-wallet
            - blur-wallet-wrapper
