name: blur-wallet
version: 0.1.9.9.1
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a privacy-focused cryptocurrency based on code from Monero. The Blur
    Network focuses on fostering an educational environment within its community,
    to lower the barriers to entry for those with an interest in cryptocurrency/mining.
    BLUR can be mined with just a CPU, and does not require specialized hardware.
    Join the Fight for Financial Freedom.
grade: stable
confinement: strict

apps:
    blurd:
        command: |
          blurd-wrapper --data-dir ${HOME}/.blurnetwork
        plugs:
            - network
            - network-bind
    blur-wallet-gui:
        command: |
          blur-wallet-wrapper
        plugs:
            - home
            - network

parts:
    blur-wallet:
        build-packages: [build-essential, git, cmake, pkg-config, libboost-all-dev, libssl-dev, libsodium-dev, qtbase5-dev, qt5-default, qtdeclarative5-dev, qml-module-qtquick-controls, qml-module-qtquick-dialogs, qml-module-qtquick-xmllistmodel, qml-module-qt-labs-folderlistmodel, qml-module-qt-labs-settings,  qttools5-dev-tools, liblzma5, libtinfo5, libunwind8, libunwind-dev]
        plugin: dump
        override-build: wget https://github.com/blur-network/blur-network-gui/releases/download/v0.1.9.9.1-snap/blur-network-gui-v0.1.9.9.1-linux-x86_64-snap.tar.gz && tar xvzf blur-network-gui-v0.1.9.9.1-linux-x86_64-snap.tar.gz && mkdir bin && cd blur-network-gui-v0.1.9.9.1-linux-x86_64 && chmod 0755 blurd-wrapper && chmod 0755 blur-wallet-wrapper && mv blurd-wrapper ../bin/blurd-wrapper && mv blur-wallet-wrapper ../bin/blur-wallet-wrapper
        source: .
        stage-packages:
            - libboost-all-dev
            - libssl-dev
            - libsodium-dev
            - libstdc++6
            - libgcc1
            - libreadline-dev
            - libunwind-dev
            - qtbase5-dev
            - qt5-default
            - qtdeclarative5-dev
            - qml-module-qtquick-controls
            - qml-module-qtquick-dialogs
            - qml-module-qtquick-xmllistmodel
            - qml-module-qt-labs-settings
            - qml-module-qt-labs-folderlistmodel
            - qttools5-dev-tools
            - liblzma5
            - libtinfo5
        prime:
            - -../parts/blur-wallet/build/bin
            - usr/lib
            - -bin
            - -usr/lib
            - -usr/share
            - -usr/share/icons/hicolor/256x256/apps
            - -usr/share/applications

    dist-files:
        plugin: dump
        source: .
        organize:
            bin: bin
            blur-network-gui-v0.1.9.9.1-linux-x86_64/blurd.conf: etc/blurd.conf
            blur-network-gui-v0.1.9.9.1-linux-x86_64/blur-gui-wallet: bin/blur-gui-wallet
            blur-network-gui-v0.1.9.9.1-linux-x86_64/blurd-wrapper: bin/blurd-wrapper
            blur-network-gui-v0.1.9.9.1-linux-x86_64/blur-wallet-wrapper: bin/blur-wallet-wrapper
            blur-network-gui-v0.1.9.9.1-linux-x86_64/start-gui.sh: bin/start-gui.sh
            blur-network-gui-v0.1.9.9.1-linux-x86_64/blur-wallet.desktop: usr/share/applications/blur-wallet.desktop
            blur-network-gui-v0.1.9.9.1-linux-x86_64/blur-icon.png: usr/share/icons/hicolor/256x256/apps/blur-icon.png
        prime:
            - -etc
            - -bin
            - -usr/share/applications
            - -usr/share/icons/hicolor/256x256/apps
