name: blur-wallet
version: 0.1.9.9.6
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a privacy-focused cryptocurrency based on code from Monero. The Blur
    Network focuses on fostering an educational environment within its community,
    to lower the barriers to entry for those with an interest in cryptocurrency/mining.
    BLUR can be mined with just a CPU, and does not require specialized hardware.
    Join the Fight for Financial Freedom.
grade: stable
confinement: strict
base: core20

apps:
    blur-wallet:
        command: blur-gui-wallet
        environment:
          PATH: ${PATH}:${SNAP}/bin
          LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/lib:${SNAP}/lib/x86_64-linux-gnu/:${SNAP}/usr/lib:${SNAP}/usr/lib/x86_64-linux-gnu/
          QT_PLUGIN_PATH: ${QT_PLUGIN_PATH}:${SNAP}/usr/lib/x86_64-linux-gnu/qt5/plugins
          QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/x86_64-linux-gnu/qt5/plugins
          QML2_IMPORT_PATH: ${QML_IMPORT_PATH}:${SNAP}/usr/lib/x86_64-linux-gnu/qt5/qml
          QT_XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb
        extensions:
            - gnome-3-38
        plugs:
            - home
            - network
            - network-bind
            - x11
            - opengl
            - desktop 
            - desktop-legacy
            - gsettings
#        slots:
#            - dbus-daemon



parts:
    blur-wallet:
        build-packages: [build-essential, git, cmake, pkg-config, libboost-serialization1.71-dev, libboost-system1.71-dev, libboost-thread1.71-dev, libboost-locale1.71-dev, libboost-filesystem1.71-dev, libboost-program-options1.71-dev, libssl-dev, libsodium-dev, qtbase5-dev, qt5-default, qtdeclarative5-dev, qml-module-qtquick-controls, qml-module-qtquick-dialogs, qml-module-qtquick-xmllistmodel, qml-module-qt-labs-folderlistmodel, qml-module-qt-labs-settings,  qttools5-dev-tools, libreadline-dev]
        plugin: dump
        filesets:
           bin-files:
             - ${SNAPCRAFT_PART_INSTALL}/bin/*
        override-build: sh -c '${SNAPCRAFT_PART_SRC}/build_snap.sh release' && mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin && cp -r ${SNAPCRAFT_PART_BUILD}/build/release/bin/* ${SNAPCRAFT_PART_INSTALL}/bin/ && cp -r ${SNAPCRAFT_PART_SRC}/blurd ${SNAPCRAFT_PART_INSTALL}/bin/
        source: .
        stage-packages:
            - libboost-filesystem1.71.0
            - libboost-program-options1.71.0
            - libboost-serialization1.71.0
            - libboost-system1.71.0
            - libboost-thread1.71.0
            - libboost-locale1.71.0
            - libssl-dev
            - libsodium23
            - libstdc++6
            - libgcc1
            - libreadline8
            - qtbase5-dev
            - qt5-default
            - qtdeclarative5-dev
            - qtquickcontrols2-5-dev
            - qml-module-qtquick-controls
            - qml-module-qtquick-controls2
            - qml-module-qtquick-templates2
            - qml-module-qtquick-dialogs
            - qml-module-qtquick-xmllistmodel
            - qml-module-qt-labs-settings
            - qml-module-qt-labs-folderlistmodel
            - qttools5-dev-tools
            - liblzma5
            - libtinfo-dev
        organize:
            local/start_gui.sh: bin/start_gui.sh
            ${SNAPCRAFT_PART_BUILD}/build/release/bin/libs/*: usr/lib/
        prime:
            - bin
            - usr/bin
            - usr/lib
            - usr/share

#slots:
#  dbus-daemon:
#    interface: dbus
#    bus: session
#    name: blur-wallet
