name: blur-wallet
version: 0.1.9.9.2
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a privacy-focused cryptocurrency based on code from Monero. The Blur
    Network focuses on fostering an educational environment within its community,
    to lower the barriers to entry for those with an interest in cryptocurrency/mining.
    BLUR can be mined with just a CPU, and does not require specialized hardware.
    Join the Fight for Financial Freedom.
grade: stable
confinement: strict
base: core18

apps:
    blur-wallet:
        command: blur-gui-wallet
        environment:
          PATH: ${PATH}:${SNAP}/bin
          LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/lib:${SNAP}/lib/x86_64-linux-gnu/:${SNAP}/usr/lib:${SNAP}/usr/lib/x86_64-linux-gnu/
          QT_PLUGIN_PATH: ${QT_PLUGIN_PATH}:${SNAP}/usr/lib/x86_64-linux-gnu/qt5/plugins
          QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/x86_64-linux-gnu/qt5/plugins
          QML2_IMPORT_PATH: ${QML_IMPORT_PATH}:${SNAP}/usr/lib/x86_64-linux-gnu/qt5/qml
        plugs:
            - home
            - network
            - network-bind
            - x11
            - opengl
            - desktop
            - desktop-legacy

parts:
    blur-wallet:
        build-packages: [build-essential, git, cmake, pkg-config, libboost-all-dev, libssl-dev, libsodium-dev, qtbase5-dev, qt5-default, qtdeclarative5-dev, qml-module-qtquick-controls, qml-module-qtquick-dialogs, qml-module-qtquick-xmllistmodel, qml-module-qt-labs-folderlistmodel, qml-module-qt-labs-settings,  qttools5-dev-tools]
        plugin: dump
        override-build: sh -c '${SNAPCRAFT_PART_SRC}/build_snap.sh release' && cp -r ${SNAPCRAFT_PART_BUILD}/release/bin ${SNAPCRAFT_PART_INSTALL}/
        source: .
        stage-packages:
            - libboost-serialization1.62.0
            - libboost-chrono1.62.0
            - libboost-atomic1.62.0
            - libboost-system1.62.0
            - libboost-filesystem1.62.0
            - libboost-locale1.62.0
            - libboost-regex1.62.0
            - libboost-date-time1.62.0
            - libboost-program-options1.62.0
            - libssl-dev
            - libsodium23
            - libstdc++6
            - libgcc1
            - libreadline-gplv2-dev
            - qtbase5-dev
            - qt5-default
            - qtdeclarative5-dev
            - qtquickcontrols2-5-dev
            - qml-module-qtquick-controls
            - qml-module-qtquick-controls2
            - qml-module-qtquick-templates2
            - qml-module-qtquick-dialogs
            - qml-module-qtquick-xmllistmodel
            - qml-module-qt-labs-settings
            - qml-module-qt-labs-folderlistmodel
            - qttools5-dev-tools
            - liblzma5
            - libtinfo5
        organize:
            local/start_gui.sh: bin/start_gui.sh
            ${SNAPCRAFT_PART_BUILD}/build/release/bin/blur-gui-wallet: ${SNAPCRAFT_PART_STAGE}/blur-gui-wallet
            ${SNAPCRAFT_PART_BUILD}/build/release/bin/blurd: ${SNAPCRAFT_PART_STAGE}/blurd
            ${SNAPCRAFT_PART_BUILD}/build/release/bin/libs/*: ${SNAPCRAFT_PART_STAGE}/usr/lib/
            ${SNAPCRAFT_PART_BUILD}/build/release/bin/plugins/*: ${SNAPCRAFT_PART_STAGE}/usr/lib/x86_64-linux-gnu/qt5/plugins/
            ${SNAPCRAFT_PART_BUILD}/build/release/bin/qml/*: ${SNAPCRAFT_PART_STAGE}/usr/lib/x86_64-linux-gnu/qt5/qml/
        prime:
            - bin
            - usr/bin
            - usr/lib
            - usr/share

    dist-files:
        plugin: dump
        source: .
        prime: 
            - blurd
            - blur-gui-wallet
            - usr/lib
